# Generated by Django 4.0 on 2023-05-18 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest', models.TextField()),
                ('sugg_a', models.CharField(max_length=150)),
                ('sugg_b', models.CharField(max_length=150)),
                ('sugg_c', models.CharField(max_length=150)),
                ('sugg_d', models.CharField(max_length=150)),
                ('res', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='qhf.category')),
            ],
        ),
    ]
